# -*- coding: utf-8 -*-
from .assets import delete_document_assets, delete_knowledge_assets
from .parsing import (
    SUPPORTED_UPLOAD_SUFFIXES,
    KnowledgeChunkModelError,
    chunk_text,
    chunk_text_with_model,
    extract_upload_payload,
)
from .embedding import cosine_similarity, embed_texts, has_usable_embedding_model
from .retrieval import build_knowledge_context, build_knowledge_message
from .soul import (
    DEFAULT_SOUL_CONTENT,
    load_soul_knowledge_config,
    save_soul_knowledge_config,
)
from .storage import (
    build_chunk_summary,
    build_document_summary,
    build_knowledge_summary,
    default_store,
    find_chunk,
    find_document,
    find_knowledge_base,
    list_chunks_paginated,
    load_store,
    normalize_knowledge_store,
    normalize_keywords,
    save_store,
    slugify,
    utc_now,
    validate_knowledge_id,
)
from .vector_config import (
    DEFAULT_CHUNK_CONFIG,
    DEFAULT_RETRIEVAL_CONFIG,
    get_upload_capabilities,
    get_vector_model_summary,
    load_knowledge_vector_config,
    normalize_chunk_config,
    normalize_retrieval_config,
    normalize_embedding_model_config,
    save_knowledge_vector_config,
)

__all__ = [
    "SUPPORTED_UPLOAD_SUFFIXES",
    "KnowledgeChunkModelError",
    "DEFAULT_CHUNK_CONFIG",
    "DEFAULT_RETRIEVAL_CONFIG",
    "DEFAULT_SOUL_CONTENT",
    "build_chunk_summary",
    "build_document_summary",
    "build_knowledge_summary",
    "build_knowledge_context",
    "build_knowledge_message",
    "chunk_text",
    "chunk_text_with_model",
    "cosine_similarity",
    "delete_document_assets",
    "delete_knowledge_assets",
    "embed_texts",
    "default_store",
    "extract_upload_payload",
    "find_chunk",
    "find_document",
    "find_knowledge_base",
    "get_upload_capabilities",
    "get_vector_model_summary",
    "has_usable_embedding_model",
    "list_chunks_paginated",
    "load_knowledge_vector_config",
    "load_soul_knowledge_config",
    "load_store",
    "normalize_chunk_config",
    "normalize_embedding_model_config",
    "normalize_retrieval_config",
    "normalize_knowledge_store",
    "normalize_keywords",
    "save_knowledge_vector_config",
    "save_soul_knowledge_config",
    "save_store",
    "slugify",
    "utc_now",
    "validate_knowledge_id",
]